import turtle

wn = turtle.Screen()
wn.setup(600,600)
wn.bgcolor('black')

snig = turtle.Turtle()
snig.shape('turtle')
snig.color('green')
#snig.speed(0)
snig.penup()
snig.goto(-100,200)
snig.pendown()
snig.write('Your face was like this..when i proposed you')
snig.penup()
snig.begin_fill()
snig.color('grey')
snig.goto(25,-150)
snig.pendown()
snig.circle(130)
snig.penup()
snig.end_fill()
snig.color('white')
snig.goto(-10,-5)
snig.begin_fill()
snig.pendown()
snig.circle(20)
snig.penup()
snig.end_fill()
snig.begin_fill()
snig.color('black')
snig.pendown()
snig.circle(10)
snig.penup()
snig.end_fill()
snig.forward(90)
snig.begin_fill()
snig.color('white')
snig.pendown()
snig.circle(20)
snig.penup()
snig.end_fill()
snig.begin_fill()
snig.color('black')
snig.pendown()
snig.circle(10)
snig.penup()
snig.end_fill()
snig.right(142)
snig.forward(90)
snig.begin_fill()
snig.color('pink')
snig.pendown()
snig.circle(30)
snig.penup()
snig.end_fill()
snig.left(47)
snig.goto(35,-25)

